BOARD = FS026
EEPROM_CUSTOM = custom
EEPROM_DRIVER = custom
NO_USB_STARTUP_CHECK = yes
BLUETOOTH_CUSTOM = yes

CONSOLE_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no

DEBOUNCE_TYPE = asym_eager_defer_pk
