MCU_FAMILY = ES32
MCU_SERIES = FS026
BOOTLOADER = custom
MCU_LDSCRIPT = FS026
MCU_STARTUP = FS026
BOARD = FS026
MCU  = cortex-m0
ARMV = 6

EEPROM_CUSTOM = custom
EEPROM_DRIVER = custom
NO_USB_STARTUP_CHECK = yes
BLUETOOTH_CUSTOM = yes

CONSOLE_ENABLE = no
MUSIC_ENABLE = no
OLED_ENABLE = no
SKIP_DEBUG_INFO = yes
DEBUG_ENABLE = no
OS_DETECTION_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk
SRC += features/layer_lock.c
SRC += features/select_word.c